In [4]:
print("***WGAN***")
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

***WGAN***


In [5]:
def preprocess(df):
    if 'Unnamed: 0' in list(df.columns.values):
        df.drop(['Unnamed: 0'], axis=1, inplace=True)
    if 'Unnamed: 0.1' in list(df.columns.values):
        df.drop(['Unnamed: 0.1'], axis=1, inplace=True)
    if 'Unnamed: 0.1.1' in list(df.columns.values):
        df.drop(['Unnamed: 0.1.1'], axis=1, inplace=True)


org_data1 = pd.read_csv("/home/ayushig/saad18409/Group1Data.csv")
org_data2 = pd.read_csv("/home/ayushig/saad18409/Group2Data.csv")
preprocess(org_data1)
preprocess(org_data2)

pca1 = PCA(n_components=20)
pca2 = PCA(n_components=20)
pca1.fit(org_data1)
pca2.fit(org_data2)

print(pca1.explained_variance_ratio_, "org1")
print(pca2.explained_variance_ratio_, "org2")






[0.14122556 0.09546811 0.05128692 0.04694211 0.04033881 0.03803928
 0.02597555 0.02186695 0.0209015  0.01736956 0.0166646  0.01417636
 0.01379063 0.01308105 0.01268039 0.01139452 0.01070845 0.01056917
 0.00965831 0.00935085] org1
[0.13346482 0.10023604 0.06474117 0.05661333 0.0287526  0.02728148
 0.02624779 0.01919782 0.0168959  0.01512339 0.01430411 0.01277789
 0.01236727 0.0119508  0.01090751 0.01042527 0.00991405 0.00981783
 0.0094232  0.00912259] org2


In [6]:
for i in [1,10,100,1000]:
    wgan_data1 = pd.read_csv(f"/home/ayushig/TB/WGAN/Group1Data/gendata/WGAN_var_test_{i}.csv")
    wgan_data2 = pd.read_csv(f"/home/ayushig/TB/WGAN/Group2Data/gendata/WGAN_var_test_{i}.csv")
    preprocess(wgan_data1)
    preprocess(wgan_data2)

    pca1 = PCA(n_components=5)
    pca2 = PCA(n_components=5)
    pca1.fit(wgan_data1)
    pca2.fit(wgan_data2)

    print(pca1.explained_variance_ratio_, f"wgan_{i}")
    print(pca2.explained_variance_ratio_, f"wgan_{i}")
    print()

wgan_data1 = pd.read_csv(f"/home/ayushig/TB/WGAN/Group1Data/gendata/WGAN_no_normal_org.csv")
wgan_data2 = pd.read_csv(f"/home/ayushig/TB/WGAN/Group2Data/gendata/WGAN_no_normal_org.csv")
preprocess(wgan_data1)
preprocess(wgan_data2)

pca1 = PCA(n_components=5)
pca2 = PCA(n_components=5)
pca1.fit(wgan_data1)
pca2.fit(wgan_data2)

print(pca1.explained_variance_ratio_, "wgan_4000")
print(pca2.explained_variance_ratio_, "wgan_4000")






[0.07497213 0.0690186  0.06035817 0.054493   0.05107567] wgan_1
[0.06838499 0.06019418 0.05272397 0.05025969 0.04458771] wgan_1

[0.13319408 0.07487604 0.06265165 0.05301091 0.05141383] wgan_10
[0.13095117 0.0616568  0.0585511  0.05632805 0.05202519] wgan_10

[0.33745284 0.09401203 0.06806519 0.05316188 0.04609421] wgan_100
[0.34643942 0.08935393 0.07284521 0.06044552 0.04543702] wgan_100

[0.4774476  0.16630924 0.10771576 0.07017597 0.0318054 ] wgan_1000
[0.38261456 0.23392128 0.11039176 0.05467921 0.04246183] wgan_1000

[0.25622965 0.15805377 0.11593708 0.09833498 0.05239901] wgan_4000
[0.22846465 0.16950052 0.10933555 0.09795708 0.05851919] wgan_4000


In [13]:
org_data1 = pd.read_csv("/home/ayushig/TB/GMMGAN/Group1Data/GMM1_83.csv")
org_data2 = pd.read_csv("/home/ayushig/TB/GMMGAN/Group2Data/GMM2_97.csv")
preprocess(org_data1)
preprocess(org_data2)

pca1 = PCA(n_components=20)
pca2 = PCA(n_components=20)
pca1.fit(org_data1)
pca2.fit(org_data2)

print(pca1.explained_variance_ratio_, "gmm1")
print(pca2.explained_variance_ratio_, "gmm2")


[0.16134396 0.10944551 0.07044947 0.05180746 0.04600862 0.03868506
 0.03254995 0.03081    0.02959319 0.02709028 0.02352119 0.02185405
 0.02127711 0.01955054 0.01798576 0.01673091 0.01560315 0.01490585
 0.01420214 0.01392991] gmm1
[0.13657541 0.09819167 0.08321334 0.07274804 0.04034893 0.0362176
 0.0318787  0.02819251 0.02409446 0.02167436 0.02015166 0.01876503
 0.01814911 0.01763763 0.01646706 0.01594537 0.01514095 0.013816
 0.01361528 0.01266313] gmm2


In [19]:
from os import name
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import os
import glob
from scipy.stats import wasserstein_distance as ssw
import scipy.stats as sst
import seaborn as sns
from sklearn.datasets import make_moons
import os
import numpy as np
import pandas as pd


class ReadDatasets:
    def __init__(self, org, gen):
        self.org = pd.read_csv(org)
        self.gen = pd.read_csv(gen)
        self.preprocess(self.org)
        self.preprocess(self.gen)
        if self.org.shape[0] != self.gen.shape[0]:
            if self.org.shape[0] > self.gen.shape[0]:
                self.org = self.org.iloc[: self.gen.shape[0], :]
            else:
                self.gen = self.gen.iloc[: self.org.shape[0], :]
        print(self.org.shape, self.gen.shape)

    def preprocess(self, df):
        if "Unnamed: 0" in list(df.columns.values):
            df.drop(["Unnamed: 0"], axis=1, inplace=True)
        if "Unnamed: 0.1" in list(df.columns.values):
            df.drop(["Unnamed: 0.1"], axis=1, inplace=True)
        if "Unnamed: 0.1.1" in list(df.columns.values):
            df.drop(["Unnamed: 0.1.1"], axis=1, inplace=True)

    def get_distances(self, X, g1, k):
        org = X.iloc[:g1, :]
        gen = X.iloc[g1:, :]
        org = org.reset_index()
        gen = gen.reset_index()
        print(org.head())
        print(gen.head())
        dist_final = []
        for i in range(len(org)):
            x1, y1 = org.loc[i,"dim1"], org.loc[i,"dim2"]
            dist_ll = []
            for j in range(len(gen)):
                x2, y2 = gen.loc[j,"dim1"], gen.loc[j,"dim2"]
                dist = np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
                dist_ll.append(dist)
            dist_ll.sort()
            dist_final.append(np.average(dist_ll[:k]))
        return np.average(dist_final)

    def plot_tsne(self, model_name, category, plotpath):
        org = self.org
        gen = self.gen
        norg = org.shape[0]
        ngen = gen.shape[0]
        label1 = ["ORG Data-{}".format(category)] * norg
        label2 = ["{} Data-{}".format(model_name, category)] * ngen
        labels = pd.Series(label1 + label2).to_frame()
        dfeatures = pd.concat([org, gen], ignore_index=True, axis=0, sort=False)
        X_embedded = TSNE(n_components=2, random_state=0, perplexity=50).fit_transform(
            dfeatures
        )
        X_embedded = pd.DataFrame(X_embedded, columns=["dim1", "dim2"])
        avg_dist = self.get_distances(X_embedded, norg, 4)
        print(avg_dist)
        X_embedded = pd.DataFrame(np.hstack([np.array(X_embedded), np.array(labels)]))
        X_embedded.columns = ["dim1", "dim2", "label"]
        sns.set(rc={"figure.figsize": (20, 80)})
        sns_fig = sns.lmplot(
            x="dim1", y="dim2", data=X_embedded, fit_reg=False, hue="label"
        )
        filename = "./"
        filename = filename + plotpath + ".png"
        plt.title(model_name)
        plt.savefig(filename, bbox_inches="tight")
        plt.close()

    # def plot_tsne2(self, name="ud", plotpath=None):
    #     actual = self.data2
    #     n_patients, n_genes = actual.shape
    #     label2 = ["Actual Data"] * n_patients
    #     labels = pd.Series(label2).to_frame()
    #     # dfeatures = pd.concat([gendata, actual], ignore_index=True,
    #     #                     axis=0, sort=False)
    #     X_embedded = TSNE(n_components=2, random_state=0, perplexity=50).fit_transform(
    #         actual
    #     )
    #     X_embedded = pd.DataFrame(X_embedded, columns=["dim1", "dim2"])
    #     X_embedded = pd.DataFrame(np.hstack([np.array(X_embedded), np.array(labels)]))
    #     X_embedded.columns = ["dim1", "dim2", "label"]

    #     sns_fig = sns.lmplot(
    #         x="dim1", y="dim2", data=X_embedded, fit_reg=False, hue="lmao"
    #     )

    #     filename = "./tsne_plot_"
    #     filename = filename + name + ".png"
    #     plt.savefig(filename)
    #     plt.close()



In [20]:

if __name__ == "__main__":

    random = [
        "/home/ayushig/TB/WGAN/Group1Data/nonormal/gendata/Random_org.csv",
        "/home/ayushig/TB/WGAN/Group2Data/nonormal/gendata/Random_org.csv",
        "/home/ayushig/TB/WGAN/Group1Axes/nonormal/gendata/Random_org.csv",
        "/home/ayushig/TB/WGAN/Group2Axes/nonormal/gendata/Random_org.csv",
    ]
    gen_wgang1 = [
        "/home/ayushig/TB/WGAN/Group1Data/gendata/WGAN_org.csv",
        "/home/ayushig/TB/WGAN/Group2Data/gendata/WGAN_org.csv",
        "/home/ayushig/TB/WGAN/Group1Axes/gendata/WGAN_Axes_org.csv",
        "/home/ayushig/TB/WGAN/Group2Axes/gendata/WGAN_Axes_org.csv",
    ]
    gen_ctgang1 = [
        "/home/ayushig/TB/CTGAN/1/gendatafin/CTGAN_org.csv",
        "/home/ayushig/TB/CTGAN/2/gendatafin/CTGAN_org.csv",
        "/home/ayushig/TB/CTGAN/1/gendatafin/CTGAN_Axes_org.csv",
        "/home/ayushig/TB/CTGAN/2/gendatafin/CTGAN_Axes_org.csv",
    ]
    gen_gmmg1 = [
        "/home/ayushig/TB/GMMGAN/Group1Data/GMM1_83.csv",
        "/home/ayushig/TB/GMMGAN/Group2Data/GMM2_97.csv",
        "/home/ayushig/TB/GMMGAN/Group1Axes/GMM1_83.csv",
        "/home/ayushig/TB/GMMGAN/Group2Axes/GMM2_97.csv",
    ]
    gen_vae1 = [
        "/home/ayushig/TB/VAE/gen_final_org1/orggendata.csv",
        "/home/ayushig/TB/VAE/gen_final_org2/orggendata.csv",
        "/home/ayushig/TB/VAE/gen_final_org1/orggendata.csv",
        "/home/ayushig/TB/VAE/gen_final_org2/orggendata.csv",
    ]
    orgg1 = [
        "/home/ayushig/saad18409/Group1Data.csv",
        "/home/ayushig/saad18409/Group2Data.csv",
        "/home/ayushig/saad18409/Group1Axes.csv",
        "/home/ayushig/saad18409/Group2Axes.csv",
    ]  # , "/home/ayushig/saad18409/Group1Axes.csv", "/home/ayushig/saad18409/Group2Axes.csv"]
    nm = ["Healthy", "TB", "Axis-Healthy", "Axis-TB"]
    iii = ["1", "2", "1", "2"]
    ii = ["", "", "Axes", "Axes"]

    rd = ReadDatasets(orgg1[0], gen_wgang1[0])
        
    # for i in range(4):
    #     rd = ReadDatasets(random[i], gen_ctgang1[i])
    #     rd.plot_tsne("CTGAN", nm[i], "CTGAN_Random_" + ii[i] + iii[i])
    # for i in range(4):
    #     rd = ReadDatasets(random[i], gen_gmmg1[i])
    #     rd.plot_tsne("GMM", nm[i], "GMM_Random_" + ii[i] + iii[i])
    # for i in range(4):
    #     rd = ReadDatasets(random[i], gen_wgang1[i])
    #     rd.plot_tsne("WGAN", nm[i], "WGAN_Random_" + ii[i] + iii[i])


(83, 34602) (83, 34602)


In [21]:
    rd.plot_tsne("wgan", nm[0], "wgan_" + ii[0] + iii[0])

.042694
-5.8627515 5.8416443
-2.5236611 -3.1445
-10.506984 -9.470787
9.65712 31.843725
-18.563246 -17.747309
-23.997543 -20.54305
8.116841 -4.84939
-17.31193 7.8834906
-1.146219 -6.3581514
-11.75248 12.376444
13.382511 3.2637968
-8.438482 2.374037
9.054175 6.5616937
-32.991024 -2.086856
-4.969829 -5.311027
0.97346306 2.10938
-10.035948 17.8241
4.8509307 5.751348
3.7737646 -10.9147005
-17.656132 -2.5227764
-24.73002 -15.977127
-36.70587 -13.213139
12.60438 -24.54372
-17.939722 40.588142
-8.8652315 -3.5646517
-14.931573 13.717129
-2.7405949 3.6577632
17.673624 31.201195
2.6342854 -0.9402661
-18.95855 12.503055
2.1131933 -6.8979692
12.996084 44.80623
2.4185774 31.852484
14.678883 21.49113
3.1822503 21.424942
0.79296505 -3.5334914
-3.816283 -9.160991
18.212547 5.8042097
3.8493683 9.43409
0.38582647 -10.216381
-1.1031858 9.877348
-7.4052906 -7.7658715
6.812438 -15.833944
0.7880031 13.85569
27.014463 29.481255 <class 'numpy.float32'>
-24.793139 -25.345524
8.693424 1.71867
-15.914482 3.088162